server:
  context-path: /uaa
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spring-cloud-demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

security:
  oauth2:
    client:
      client-id: spring-cloud-demo-auth-client_id
      client-secret : spring-cloud-demo-auth-secret
    authorization:
      checkTokenAccess : isAuthenticated()